name: CI
on:
  push:
    branches-ignore:
      - main

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.1'
     
      - name: Install rubocop
        run: gem install rubocop

      - name: Linting
        working-directory: ./src
        run: rubocop

